package study;

import java.util.Arrays;

import logic.BubbleSort;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public static void main(String[] args) {
        BubbleSort<String> sort = new BubbleSort<>();
        System.out.println("[result]" + sort.sort(Arrays.asList(args)));
        
    }
}
